//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_01_Akhmatova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Building()
        {
            this.Apartment = new HashSet<Apartment>();
        }
    
        public int BuildingId { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> ManagementStartDate { get; set; }
        public Nullable<short> Floors { get; set; }
        public Nullable<short> ApartmentsPlanned { get; set; }
        public Nullable<short> BuildYear { get; set; }
        public Nullable<decimal> AreaM2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartment> Apartment { get; set; }
    }
}
