//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_01_Akhmatova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int ResidentId { get; set; }
        public int ApartmentId { get; set; }
        public System.DateTime PeriodDate { get; set; }
        public decimal Accrued { get; set; }
        public Nullable<decimal> Paid { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Resident Resident { get; set; }
    }
}
