//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_01_Akhmatova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RequestHistory = new HashSet<RequestHistory>();
        }
    
        public int RequestId { get; set; }
        public int ApartmentId { get; set; }
        public Nullable<int> ApplicantResidentId { get; set; }
        public string ApplicantFullName { get; set; }
        public string ApplicantPhone { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> AssignedEmployeeId { get; set; }
        public byte StatusId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Resident Resident { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestHistory> RequestHistory { get; set; }
    }
}
