//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_01_Akhmatova
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHistory
    {
        public int HistoryId { get; set; }
        public int RequestId { get; set; }
        public System.DateTime ChangedAt { get; set; }
        public byte StatusId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Comment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Request Request { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
    }
}
