//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_01_Akhmatova
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRequestHistoryByAddress
    {
        public string Address { get; set; }
        public int ApartmentNumber { get; set; }
        public int RequestId { get; set; }
        public string StatusName { get; set; }
        public string ApplicantFullName { get; set; }
        public string ApplicantPhone { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> AssignedEmployeeId { get; set; }
        public string AssignedEmployeeName { get; set; }
        public System.DateTime ChangedAt { get; set; }
        public string Comment { get; set; }
    }
}
