//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_01_Akhmatova
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRequestHistoryByEmployee
    {
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public int RequestId { get; set; }
        public string Address { get; set; }
        public int ApartmentNumber { get; set; }
        public string StatusName { get; set; }
        public System.DateTime ChangedAt { get; set; }
        public string Comment { get; set; }
    }
}
